# enable the 'trusty beta' VM to access a modern gcc
dist: trusty
sudo: required

# setup for C++
language: c++
compiler:
  - clang
  - gcc

# install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libhdf5-dev

# the actual build and test process
script:
  - mkdir build
  - cd build
  - cmake .. && make
